#!/bin/bash
set -e

# Log all output
exec > >(tee /var/log/user-data.log)
exec 2>&1

echo "Starting user-data script at $(date)"

# Update system packages
echo "Updating system packages..."
apt-get update
apt-get upgrade -y

# Install required packages
echo "Installing required packages..."
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    git \
    jq \
    unzip \
    htop

# Install Docker
echo "Installing Docker..."
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
usermod -aG docker ubuntu
systemctl enable docker
systemctl start docker

# Install Docker Compose
echo "Installing Docker Compose..."
DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)
curl -L "https://github.com/docker/compose/releases/download/$${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Create project directory
echo "Creating project directory..."
PROJECT_DIR="/home/ubuntu/traefik-otel-demo"
mkdir -p $PROJECT_DIR
chown -R ubuntu:ubuntu $PROJECT_DIR

# Create .env file with Elastic Cloud credentials
echo "Creating .env file..."
cat > $PROJECT_DIR/.env <<'ENVEOF'
# Elastic Cloud Endpoints
ELASTIC_ENDPOINT=${elastic_endpoint}
ELASTIC_USERNAME=${elastic_username}
ELASTIC_PASSWORD=${elastic_password}
KIBANA_ENDPOINT=${kibana_endpoint}

# Elastic API Key (will be auto-generated by deploy script)
ELASTIC_API_KEY=PLACEHOLDER
ENVEOF

chown ubuntu:ubuntu $PROJECT_DIR/.env

# Create completion marker
echo "User-data script completed successfully at $(date)" > /var/log/user-data-complete.log

echo "User-data script finished at $(date)"
